# Generated by Django 4.1.4 on 2022-12-31 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("release_date", models.DateField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("toyline", models.CharField(max_length=255)),
                ("size_class", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[("H", "Hasbro"), ("T", "Takara Tomy")], max_length=1
                    ),
                ),
            ],
        ),
    ]
