# Generated by Django 4.1.4 on 2022-12-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformer",
            name="picture",
            field=models.ImageField(null=True, unique=True, upload_to=""),
        ),
    ]
