# Generated by Django 4.1.4 on 2023-01-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transformers", "0003_alter_transformer_options_transformer_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transformer", options={"ordering": ("name",)},
        ),
    ]
