# Generated by Django 4.1.4 on 2023-01-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformers", "0004_alter_transformer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformer",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
