# Generated by Django 4.1.4 on 2023-01-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transformers", "0005_transformer_is_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Toyline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Subline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "toyline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transformers.toyline",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transformer",
            name="subline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transformers.subline",
            ),
        ),
        migrations.AlterField(
            model_name="transformer",
            name="toyline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transformers.toyline",
            ),
        ),
    ]
