# Generated by Django 4.1.4 on 2023-01-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transformers", "0007_alter_subline_name_alter_toyline_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transformer",
            name="subline",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="transformers.subline",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="transformer",
            name="toyline",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="transformers.toyline",
                to_field="name",
            ),
        ),
    ]
