# Generated by Django 4.1.5 on 2023-01-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformers", "0011_transformer_newginindex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transformer",
            name="picture",
            field=models.ImageField(null=True, unique=True, upload_to="transformers"),
        ),
    ]
