# Generated by Django 4.1.5 on 2023-01-31 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        choices=[
                            ("E", "Everyone"),
                            ("F", "Friends Only"),
                            ("N", "No One"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("E", "Everyone"),
                            ("F", "Friends Only"),
                            ("N", "No One"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
