# Generated by Django 4.1.4 on 2022-12-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="useraccount", name="id",),
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
