# Generated by Django 4.1.5 on 2023-03-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_useraccount_id_alter_useraccount_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="username",
            field=models.CharField(default="dagleaves", max_length=50),
            preserve_default=False,
        ),
    ]
