# Generated by Django 4.1.5 on 2023-02-08 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transformers", "0012_alter_transformer_picture"),
        ("tfcollections", "0002_alter_collection_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="transformer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transformers.transformer",
            ),
        ),
    ]
