# Generated by Django 4.1.5 on 2023-02-08 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tfcollections", "0003_alter_collectionitem_transformer"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="collection",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="tfcollections.collection",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="collection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
