# Generated by Django 4.1.5 on 2023-03-04 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tfcollections", "0004_collectionitem_collection_alter_collection_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
